##
## Makefile to compile local files and copy binaries 
## to project release directory
##

ROOT := ../

SOURCES =
SOURCES += epool.erl
SOURCES += epool_sup.erl
SOURCES += epool_supersup.erl
SOURCES += epool_srv.erl
SOURCES += epool_workers_sup.erl
SOURCES += epool_example_worker.erl
SOURCES += epool_example.erl
SOURCES +=


include $(ROOT)include/src_make.mk

